name: moody
description: Google Developer Student Clubs 23 HACKATHON
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_heatmap_calendar: ^1.0.5
  http: ^0.13.5
  flutter_secure_storage: ^7.0.1
  intl: ^0.18.0
  rive: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/riv/check.riv
   
  fonts:
     - family: NotoSans
       fonts:
         - asset: assets/fonts/NotoSansKR-Thin.otf
           weight: 100
         - asset: assets/fonts/NotoSansKR-Light.otf
           weight: 300
         - asset: assets/fonts/NotoSansKR-Regular.otf
           weight: 400
         - asset: assets/fonts/NotoSansKR-Medium.otf
           weight: 500
         - asset: assets/fonts/NotoSansKR-Bold.otf
           weight: 700
         - asset: assets/fonts/NotoSansKR-Black.otf
           weight: 900
